name: bactrack
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<=3.11
  - pytorch
  - torchvision
  - cellpose>=2.2.3
  - numpy
  - pandas
  - Pillow
  - scikit-learn
  - setuptools
  - scikit-image
  - pytorch
  - tqdm
  - psutil
  - scipy
  - opencv
  - pip:
    - git+https://github.com/kevinjohncutler/omnipose.git
    - mip

