name: bactrack
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - cellpose>=2.2.3
  - numpy
  - pandas
  - Pillow
  - scikit-learn
  - setuptools
  - scikit-image
  - pytorch
  - tqdm
  - psutil
  - scipy
  - opencv
  - torchvision
  - pip:
    - omnipose
    - mip

