name: bactrack
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.10.14
  - pytorch
  - torchvision
  - cellpose>=2.2.3
  - numpy
  - pandas
  - Pillow
  - scikit-learn
  - setuptools
  - scikit-image
  - pytorch
  - tqdm
  - psutil
  - scipy
  - opencv
  - cffi==1.15.0
  - shapely
  - descartes
  - ipywidgets
  - pip
  - pip:
    - git+https://github.com/kevinjohncutler/omnipose.git
    - mip
    - mpl_interactions
    - pyqt5
    - pyqt6
