name: Python package

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yaml
        activate-environment: bactrack
        auto-activate-base: false

    - name: Run Tests
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate bactrack
        conda list
        pytest
